version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - FLASK_DEBUG=False
      - MODEL_LOAD_NAME=NLLB-rup-ron-eng-ct2-v2
      - MAX_INPUT_TOKENS=1024
      - BATCH_SIZE=4
      - MAX_OUTPUT_TOKENS=1024
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
      - MEMCACHED_URI=memcached://memcached:11211
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: "flask --app app run"
    networks:
      - net
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
    networks:
      - net

networks:
  net:
    driver: bridge
