name: Build and publish latest image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make a previous version
        run: |
            echo ${GITHUB_HEAD_REF-${GITHUB_REF##*/}}
            echo ${GITHUB_REF##*/}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/arotranslate:latest && \
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/arotranslate:latest ${{ secrets.DOCKERHUB_USERNAME }}/arotranslate:previous && \
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/arotranslate:previous

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: deployment
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/arotranslate:latest
