name: Deploy to QA
on:
  # the 1st condition
  workflow_run:
    workflows: ["Build and publish latest image"]
    branches: [main]
    types:
      - completed

jobs:
  deploy_to_unibuc:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CI_PULL_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.CI_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and deploy
        run: ssh ${{ secrets.CI_SSH_USER }}@${{ secrets.CI_SSH_HOST }} "cd /home/snisioi/aromanian/arotransweb_latest/deployment && ./pull_and_deploy.sh"